export const AZURE_SUBSCRIPTION_ID = process.env.AZURE_SUBSCRIPTION_ID;
export const AZURE_RESOURCE_GROUP = process.env.AZURE_RESOURCE_GROUP;
export const AZURE_COSMOSDB_ACCOUNT_NAME = process.env.AZURE_COSMOSDB_ACCOUNT_NAME;
